plugins:
  - jekyll-paginate
  - jekyll-gist

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            "TE Connectivity"
tagline:          'A Jekyll theme'
description:      'is a global leader in connectivity and sensor solutions, supplying a wide range of high-performance electronic components, connectors, and sensors.'
url:              ""
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5




